language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.4.16
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO_VERSION=1.4.16
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r test_requirements.txt
  - pip install -e .
script: make test
