sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.8.8
  - DJANGO_VERSION=1.9.1
  - DJANGO_VERSION=2.0.0
install:
  - pip install -q Django~=$DJANGO_VERSION
  - pip install -e .
script: make test
