sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r test_requirements.txt
  - pip install -e .
script: make test
